# Generated by Django 4.1.7 on 2023-04-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='operation',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='', max_length=4),
        ),
    ]
