# Generated by Django 4.1.7 on 2023-04-06 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_asset_amount_alter_asset_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='operation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
